environment: production
kusama:
  db:
    uri: "mongodb://<path:vaults/k8s-community-secrets/items/otv-kusama#mongo-username>:<path:vaults/k8s-community-secrets/items/otv-kusama#mongo-password>@kusama-mongodb.kusama/otv?tls=false"        
  be:
    nominating: true
    secret:  <path:vaults/k8s-community-secrets/items/otv-kusama#backend-secret>
    domain: kusama.w3f.community
    matrix:   
      room: "!mdugGIKqSTweIOpTlA:web3.foundation"
      userId: "@1kvbot:web3.foundation"
    storage: "20Gi"
    resources:
      limits:
        cpu: "3500m"
        memory: "9Gi"
      requests:
        cpu: "700m"
        memory: "3Gi"      
  mongoExpress:
    whitelistSourceIps: <path:vaults/k8s-community-secrets/items/otv-kusama#shared-vpn-ip>
    domain: w3f.community
polkadot: 
  db:
    uri: "mongodb://<path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-username>:<path:vaults/k8s-community-secrets/items/otv-polkadot#mongo-password>@polkadot-mongodb.polkadot/otv?tls=false" 
  be:
    nominating: true
    secret:  <path:vaults/k8s-community-secrets/items/otv-polkadot#backend-secret>
    domain: polkadot.w3f.community
    matrix:   
      room: "!ccXWsugXuoiHnkEhKa:web3.foundation"
      userId: "@1kvbot:web3.foundation"
    storage: "20Gi"
    resources:
      limits:
        cpu: "3500m"
        memory: "9Gi"
      requests:
        cpu: "700m"
        memory: "3Gi"      
  mongoExpress:
    whitelistSourceIps: <path:vaults/k8s-community-secrets/items/otv-polkadot#shared-vpn-ip>
    domain: w3f.community
